export const LOGIN_BEGIN = "LOGIN_BEGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const RESET_LOGIN = "RESET_LOGIN"

export const LOGOUT_BEGIN = "LOGOUT_BEGIN"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "LOGOUT_ERROR"
export const RESET_LOGOUT = "RESET_LOGOUT"