export const CREATE_NOTE_BEGIN = "CREATE_NOTE_BEGIN"
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS"
export const CREATE_NOTE_ERROR = "CREATE_NOTE_ERROR"
export const RESET_CREATE_NOTE = "RESET_CREATE_NOTE"

export const DELETE_NOTE_BEGIN = "DELETE_NOTE_BEGIN"
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS"
export const DELETE_NOTE_ERROR = "DELETE_NOTE_ERROR"
export const RESET_DELETE_NOTE = "RESET_DELETE_NOTE"

export const EDIT_NOTE_BEGIN = "EDIT_NOTE_BEGIN"
export const EDIT_NOTE_SUCCESS = "EDIT_NOTE_SUCCESS"
export const EDIT_NOTE_ERROR = "EDIT_NOTE_ERROR"
export const RESET_EDIT_NOTE = "RESET_EDIT_NOTE"

export const FETCH_NOTES_BEGIN = "FETCH_NOTES_BEGIN"
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS"
export const FETCH_NOTES_ERROR = "FETCH_NOTES_ERROR"
export const RESET_FETCH_NOTES = "RESET_FETCH_NOTES"

export const FETCH_NOTE_DETAILS_BEGIN = "FETCH_NOTE_DETAILS_BEGIN"
export const FETCH_NOTE_DETAILS_SUCCESS = "FETCH_NOTE_DETAILS_SUCCESS"
export const FETCH_NOTE_DETAILS_ERROR = "FETCH_NOTE_DETAILS_ERROR"